// ── AI Image Generation (DALL-E 3) ────────────────────────────
const OpenAI  = require('openai');
const config  = require('../../config');
const fetch   = require('node-fetch');

let openai;
if (config.OPENAI_API_KEY) openai = new OpenAI({ apiKey: config.OPENAI_API_KEY });

module.exports = {
  name:    'imagine',
  aliases: ['aiimage', 'dalle', 'generate'],
  category: 'ai',
  desc:    'Generate an image with DALL-E 3',
  usage:   '.imagine [prompt]',
  public:  true,

  async execute({ sock, msg, from, args }) {
    if (!openai) {
      return sock.sendMessage(from, { text: '🖼️ Image generation requires OpenAI API key.' }, { quoted: msg });
    }
    const prompt = args.join(' ');
    if (!prompt) {
      return sock.sendMessage(from, { text: '⚠️ Provide a prompt. Example: .imagine a sunset over Lagos' }, { quoted: msg });
    }

    await sock.sendMessage(from, { text: '🎨 Generating your image...' }, { quoted: msg });
    await sock.sendPresenceUpdate('composing', from);

    try {
      const res = await openai.images.generate({
        model:   'dall-e-3',
        prompt,
        n:       1,
        size:    '1024x1024',
        quality: 'standard',
      });

      const imageUrl = res.data[0].url;
      const imgRes   = await fetch(imageUrl);
      const buffer   = Buffer.from(await imgRes.arrayBuffer());

      return sock.sendMessage(from, {
        image:   buffer,
        caption: `🎨 *Generated by APEX AI*\n📝 Prompt: ${prompt}`,
      }, { quoted: msg });
    } catch (err) {
      return sock.sendMessage(from, { text: `⚠️ Image generation failed: ${err.message}` }, { quoted: msg });
    }
  },
};
